import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, Box, CircleDot, Hash, Pause, Play, RotateCcw, SkipForward, GitBranch } from 'lucide-react';

export type DSAAlgorithm = 'BFS' | 'DFS' | 'Queue' | 'Stack' | 'Linked List' | 'Hash Table' | 'Max Heap';
export type DSAEvent = { type:string; algorithm:string; step:number; nodeId:string|null; edgeId:string|null; parentNodeId:string|null; queueSize:number; stackSize:number; visitedCount:number; size:number; bucket:number; collisionCount:number; key:string|null; value:string|null; message:string };
export type DSATrace = { algorithm:string; sourceNodeId?:string; destinationNodeId?:string; reachable?:boolean; sourceEqualsDestination?:boolean; visitOrder?:string[]; pathNodes?:string[]; pathEdges?:string[]; events:DSAEvent[] };
export type DSAFrame = { algorithm:DSAAlgorithm; event:DSAEvent|null; eventIndex:number; currentNodeId:string|null; visited:Set<string>; discovered:Set<string>; activeEdgeId:string|null; finalNodes:Set<string>; finalEdges:Set<string>; queueSize:number; stackSize:number; visitedCount:number; complete:boolean; unreachable:boolean };

const speeds = { Slow:900, Normal:350, Fast:120 } as const;
const files:Record<DSAAlgorithm,string> = { BFS:'bfs-events', DFS:'dfs-events', Queue:'queue-events', Stack:'stack-events', 'Linked List':'linkedlist-events', 'Hash Table':'hashtable-events', 'Max Heap':'emergency-simulation-demo' };

type Props={algorithm:DSAAlgorithm;sourceNodeId:string;destinationNodeId:string;onFrame:(frame:DSAFrame)=>void;onClose:()=>void;onOpenDijkstra:()=>void};

const dsaInfo: Record<DSAAlgorithm, { role: string; how: string; time: string; space: string; example: string }> = {
  BFS: { role: 'Minimum-hop emergency reachability', how: 'Manual FIFO Queue expands the graph level by level.', time: 'O(V + E)', space: 'O(V)', example: 'Network reachability / topology exploration' },
  DFS: { role: 'Emergency network exploration', how: 'Manual Stack drives iterative depth-first exploration.', time: 'O(V + E)', space: 'O(V)', example: 'Deep graph exploration and traversal tracing' },
  Queue: { role: 'Emergency intake / waiting work', how: 'Manual circular array preserves FIFO order.', time: 'Enqueue O(1) · Dequeue O(1)', space: 'O(n)', example: 'Incoming incidents waiting for coordinator processing' },
  Stack: { role: 'DFS / action-history support', how: 'Manual dynamic stack exposes LIFO operations.', time: 'Push O(1) · Pop O(1)', space: 'O(n)', example: 'DFS traversal frontier / LIFO exploration' },
  'Linked List': { role: 'Resolved incident history', how: 'Manual nodes link lifecycle history without std::list.', time: 'Insert front O(1) · Search O(n)', space: 'O(n)', example: 'Closed incidents appended to operational history' },
  'Hash Table': { role: 'Fast incident lookup', how: 'Manual hashing with separate chaining handles collisions.', time: 'Average O(1) · Worst O(n)', space: 'O(n + buckets)', example: 'Incident ID → compact incident record lookup' },
  'Max Heap': { role: 'Emergency priority scheduling', how: 'Manual binary Max Heap keeps the highest priority at the root.', time: 'Insert/Extract O(log n) · Peek O(1)', space: 'O(n)', example: 'Coordinator PROCESS NEXT selection' }
};


export default function DSAVisualizer({algorithm,sourceNodeId,destinationNodeId,onFrame,onClose,onOpenDijkstra}:Props){
 const [activeAlgorithm,setActiveAlgorithm]=useState<DSAAlgorithm>(algorithm);
 const [trace,setTrace]=useState<DSATrace|null>(null);const [index,setIndex]=useState(-1);const [playing,setPlaying]=useState(false);const [speed,setSpeed]=useState<keyof typeof speeds>('Normal');const [error,setError]=useState('');const timer=useRef<number|null>(null);
 useEffect(()=>{let alive=true;const isTraversal=activeAlgorithm==='BFS'||activeAlgorithm==='DFS';const url=isTraversal?`/data/${files[activeAlgorithm]}-${sourceNodeId}-${destinationNodeId}.json`:`/data/${files[activeAlgorithm]}.json`;fetch(url,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json() as Promise<DSATrace>}).then(data=>{if(alive){const next=activeAlgorithm==='Max Heap'?{...data,algorithm:'Max Heap',events:data.events.filter((x: DSAEvent) => x.type.startsWith('MAX_HEAP_'))}:data;setTrace(next);setIndex(-1);setPlaying(false);setError('')}}).catch(()=>alive&&setError('Pre-generated C++ trace is unavailable. Generate the required trace with crisismesh_trace_exporter.'));return()=>{alive=false}},[activeAlgorithm,sourceNodeId,destinationNodeId]);
 const frame=useMemo<DSAFrame>(()=>{const ev=trace?.events??[];const i=Math.max(-1,Math.min(index,ev.length-1));const visited=new Set<string>(),discovered=new Set<string>(),finalNodes=new Set<string>(),finalEdges=new Set<string>();let currentNodeId:string|null=null,activeEdgeId:string|null=null,queueSize=0,stackSize=0,visitedCount=0,complete=false,unreachable=false; if(trace?.sourceNodeId)discovered.add(trace.sourceNodeId);for(let j=0;j<=i;j++){const e=ev[j];queueSize=e.queueSize||((activeAlgorithm==='Queue')?e.size:0);stackSize=e.stackSize||((activeAlgorithm==='Stack')?e.size:0);visitedCount=e.visitedCount;if(e.nodeId&&['BFS_DEQUEUE','BFS_CURRENT_NODE','BFS_NODE_DISCOVERED','DFS_POP','DFS_CURRENT_NODE','DFS_NODE_DISCOVERED'].includes(e.type))currentNodeId=e.nodeId;if(e.type.includes('NODE_DISCOVERED')&&e.nodeId)discovered.add(e.nodeId);if((e.type==='BFS_CURRENT_NODE'||e.type==='DFS_CURRENT_NODE')&&e.nodeId)visited.add(e.nodeId);if(e.type.includes('EDGE_EXAMINED'))activeEdgeId=e.edgeId;if(e.type==='BFS_DESTINATION_REACHED'||e.type==='DFS_DESTINATION_REACHED')finalNodes.add(e.nodeId??'');if(e.type==='BFS_COMPLETE'||e.type==='DFS_COMPLETE')complete=true;if(e.type.includes('UNREACHABLE'))unreachable=true;}if(trace?.pathNodes&&complete)trace.pathNodes.forEach(n=>finalNodes.add(n));if(trace?.pathEdges&&complete)trace.pathEdges.forEach(e=>finalEdges.add(e));return{algorithm:activeAlgorithm,event:i>=0?ev[i]:null,eventIndex:i,currentNodeId,visited,discovered,activeEdgeId,finalNodes,finalEdges,queueSize,stackSize,visitedCount,complete,unreachable}},[trace,index,activeAlgorithm]);
 useEffect(()=>{onFrame(frame)},[frame,onFrame]);useEffect(()=>{if(!playing||!trace)return;if(index>=trace.events.length-1){setPlaying(false);return}timer.current=window.setTimeout(()=>setIndex(v=>Math.min(v+1,trace.events.length-1)),speeds[speed]);return()=>{if(timer.current)window.clearTimeout(timer.current)}},[playing,index,speed,trace]);
 const step=()=>trace&&setIndex(v=>Math.min(v+1,trace.events.length-1));const reset=()=>{setPlaying(false);setIndex(-1)};const progress=trace?Math.max(0,((index+1)/trace.events.length)*100):0;const e=frame.event;
 return <div className="dsa-lab-panel" role="dialog" aria-label="CrisisMesh DSA visualization">
   <div className="dsa-lab-head"><div><span className="eyebrow">C++17 DSA / PRE-GENERATED TRACE LAB</span><h3><Activity size={15}/> DSA VISUALIZATION</h3><small>{activeAlgorithm} / {activeAlgorithm==='BFS'||activeAlgorithm==='DFS'?`${sourceNodeId} → ${destinationNodeId}`:'CrisisMesh operational structure'}</small></div><button onClick={onClose} aria-label="Close DSA execution lab">×</button></div>
   <div className="dsa-tabs"><button onClick={onOpenDijkstra}>DIJKSTRA</button><button className={activeAlgorithm==='BFS'?'active':''} onClick={()=>setActiveAlgorithm('BFS')}>BFS</button><button className={activeAlgorithm==='DFS'?'active':''} onClick={()=>setActiveAlgorithm('DFS')}>DFS</button><span/> <button className={activeAlgorithm==='Queue'?'active':''} onClick={()=>setActiveAlgorithm('Queue')}>QUEUE</button><button className={activeAlgorithm==='Stack'?'active':''} onClick={()=>setActiveAlgorithm('Stack')}>STACK</button><button className={activeAlgorithm==='Linked List'?'active':''} onClick={()=>setActiveAlgorithm('Linked List')}>LINKED LIST</button><button className={activeAlgorithm==='Hash Table'?'active':''} onClick={()=>setActiveAlgorithm('Hash Table')}>HASH TABLE</button><button className={activeAlgorithm==='Max Heap'?'active':''} onClick={()=>setActiveAlgorithm('Max Heap')}>MAX HEAP</button></div>
   {error?<div className="dijkstra-error">{error}</div>:<>
     <div className="dijkstra-progress"><i style={{width:`${progress}%`}}/></div>
     <div className="dijkstra-controls"><button onClick={()=>setPlaying(v=>!v)} disabled={!trace}>{playing?<Pause size={13}/>:<Play size={13}/>} {playing?'PAUSE':'RUN'}</button><button onClick={step} disabled={!trace||index>=(trace?.events.length??0)-1}><SkipForward size={13}/> STEP</button><button onClick={reset}><RotateCcw size={13}/> RESET</button><select value={speed} onChange={e=>setSpeed(e.target.value as keyof typeof speeds)}><option>Slow</option><option>Normal</option><option>Fast</option></select></div>
     <div className="dsa-live-grid"><div><span>EVENT</span><b>{e?.type??'READY'}</b></div><div><span>CURRENT</span><b>{frame.currentNodeId??'—'}</b></div><div><span>QUEUE</span><b>{frame.queueSize}</b></div><div><span>STACK</span><b>{frame.stackSize}</b></div><div><span>VISITED</span><b>{frame.visitedCount}</b></div><div><span>TRACE STATE</span><b>{frame.unreachable?'UNREACHABLE':frame.complete?'COMPLETE':index < 0 ? 'READY' : 'PLAYING'}</b></div></div>
     {(activeAlgorithm==='BFS'||activeAlgorithm==='DFS')&&<div className="dsa-structure-visual"><div className="analysis-title"><Box size={13}/> {activeAlgorithm==='BFS'?'QUEUE FRONTIER':'STACK TOP'}</div><div className="structure-strip">{activeAlgorithm==='BFS'?<><i>FRONT</i><b>{frame.queueSize} ITEMS</b><i>REAR</i></>:<><i>TOP</i><b>{frame.stackSize} ITEMS</b><i>BOTTOM</i></>}</div></div>}
     {activeAlgorithm==='Linked List'&&<div className="dsa-structure-visual"><div className="analysis-title"><CircleDot size={13}/> INCIDENT EVENT HISTORY</div><div className="linked-flow"><b>HEAD</b><span>REPORTED</span><i>→</i><span>TRIAGED</span><i>→</i><span>QUEUED</span><i>→</i><span>ASSIGNED</span><i>→ NULL</i></div></div>}
     {activeAlgorithm==='Hash Table'&&<div className="dsa-structure-visual"><div className="analysis-title"><Hash size={13}/> INCIDENT HASH BUCKETS</div><div className="hash-buckets">{[0,1,2,3,4].map(b=><div key={b}><em>{b}</em><span>{e?.bucket===b&&e.key?e.key:'—'}</span></div>)}</div><small>Separate chaining · bucket {e?.bucket ?? '—'} · collision count: {e?.collisionCount??0}</small></div>} 
     {activeAlgorithm==='Max Heap'&&<div className="dsa-structure-visual maxheap-visual"><div className="analysis-title"><GitBranch size={13}/> INCIDENT PRIORITY MAX HEAP <small>actual C++ heap snapshot</small></div><div className="heap-array">{(e?.value?e.value.split('|'):[]).map((item,i)=>{const [id,priority]=item.split(':');return <b key={item}><span>{i}</span>{id}<em>{priority}</em></b>})}</div><div className="heap-tree">{(e?.value?e.value.split('|').slice(0,7):[]).map((item,i)=>{const [id,priority]=item.split(':');return <b key={'t'+item} className={`heap-level level-${Math.floor(Math.log2(i+1))}`} style={{gridColumn:i+1}}>{id}<em>{priority}</em></b>})}</div><small>Insert/extract/compare/swap events are emitted by the manual C++ Max Heap. The array shown is the C++ heap snapshot returned in the trace.</small></div>}
     <div className="dsa-analysis dsa-explainer"><div className="analysis-title">{activeAlgorithm.toUpperCase()} / CRISISMesh ROLE</div><p className="dsa-role">{dsaInfo[activeAlgorithm].role}</p><p className="dsa-how">{dsaInfo[activeAlgorithm].how}</p><div className="analysis-grid"><span>TIME <b>{dsaInfo[activeAlgorithm].time}</b></span><span>SPACE <b>{dsaInfo[activeAlgorithm].space}</b></span><span>OPERATION <b>{e?.type??'READY'}</b></span><span>EVENT STEP <b>{e ? index + 1 : '—'}</b></span></div><div className="dsa-real-example"><span>REAL SYSTEM EXAMPLE</span><b>{dsaInfo[activeAlgorithm].example}</b></div></div>
     {e&&<div className="dijkstra-event"><span>{String(index+1).padStart(3,'0')}</span><p>{e.message}</p><b>{e.type}</b></div>}
   </>}
 </div>
}
